# This is a basic workflow to help you get started with Actions

name: "Newman Tests"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run API Tests
        run: newman run LibraryBook.postman_collection -d BookData.csv -e QA.postman_environment -g libraryworkspace.postman_globals -r htmlextra
